### ISSUE TITLE
LockedJoint should not always have a varying right hand side

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-manipulation#45]
Consider two states and one transition, with the following constraints:
- state A: no constraints
- state B: lock dof nb 0
- A->B: no constraints

Then, `graph.generateTargetConfig('A->B', qleaf, qrand)` changes the value of the locked joint to be qleaf[0]. This value may be different from the one in state B.

More generally, it should not be possible to change the right hand side of a constraint in a state. This could be checked in C++ class Edge.

**Comment by florent-lamiraux** [comment]
I do not agree with the proposition : "graph.generateTargetConfig('A->B', qleaf, qrand) changes the value of the locked joint to be qleaf[0]. This value may be different from the one in state B."

If I do not mistake, as the transition has no constraint, "generateTargetConfig will return a configuration with the lock dof value corresponding to state B.

Anyway, I agree that a locked joint should not always have a varying right hand side

**Comment by jmirabel** [comment]
> I do not agree with the proposition : "graph.generateTargetConfig('A->B', qleaf, qrand) changes the value of the locked joint to be qleaf[0]. This value may be different from the one in state B."
>
> If I do not mistake, as the transition has no constraint, "generateTargetConfig will return a configuration with the lock dof value corresponding to state B.

The config projector used to generate a target configuration contains constraints from state B and transition A->B. And we do `configProjector->rightHandSideFromConfig(qleaf)`.

I encountered the issue yesterday.

**Comment by jmirabel** [comment]
> Anyway, I agree that a locked joint should not always have a varying right hand side

This has been addressed.

> More generally, it should not be possible to change the right hand side of a constraint in a state. This could be checked in C++ class Edge.

This has not been addressed.

**Comment by florent-lamiraux** [comment]
I think this issue has been solved when making LockedJoint derive from Explicit in hpp-constraint. The constructor sets the comparison type to Equality for all degrees of freedom:
https://github.com/humanoid-path-planner/hpp-constraints/blob/8fa06ebd5fdbafbd48fb708fd5c586d8fd48672c/src/locked-joint.cc#L140, and
https://github.com/humanoid-path-planner/hpp-constraints/blob/8fa06ebd5fdbafbd48fb708fd5c586d8fd48672c/src/locked-joint.cc#L174.

@jmirabel : do you agree ?

**Comment by jmirabel** [comment]
This problem related to the LockedJoint, yes but this one, although a but out of scope, is still not solved

> More generally, it should not be possible to change the right hand side of a constraint in a state. This could be checked in C++ class Edge.

It may be moved into another issue.

**Comment by florent-lamiraux** [comment]
We could reimplement State::addNumericalConstraint, throw an exception if the input constraint is parameterizable, and copy the constraint to make sure that nobody will modify it ?

**Comment by jmirabel** [comment]
> We could reimplement State::addNumericalConstraint

This is an option. We can also do the check in:
- buildConfigConstraint and/or buildPathConstraint,
- the graph validation procedure.

I don't know what's the most appropriate.

>  copy the constraint to make sure that nobody will modify it

I would prefer not to do it.

**Comment by florent-lamiraux** [comment]
Solved by https://github.com/humanoid-path-planner/hpp-manipulation/pull/99.
